
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netflix-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/limanalhassann/local-argocd.git'
    path: Netflix
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: netflix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true