apiVersion: v1
kind: Service
metadata:
  labels:
    app: mario
  name: mario-service
  namespace: mario
spec:
  type: NodePort
  ports:
  - nodePort: 32000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mario
